<a href="https://colab.research.google.com/github/hyeonyeongjung/2024-DLP/blob/main/inclass/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 텐서플로 기본 pdf p.19까지

In [1]:
import tensorflow as tf

a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = a + b

with tf.Session() as sess:
  print(sess.run(c, {a: [1, 2, 3]}))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32, shape=3)
b = tf.Variable(3)
c = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [1, 2, 3]}))

[4 5 6]


In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.multiply(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [[1, 2, 3], [1, 2, 3], [1, 2, 3]], b: [[1, 2, 3], [1, 2, 3], [1, 2, 3]]}))

[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [22]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.add(a,b)
d = tf.subtract(a,b)
e = tf.multiply(a,b)
f = tf.div(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print("Plus => ", (sess.run(c, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]})))
  print("Minus => ", (sess.run(d, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]})))
  print("Mutiply => ", (sess.run(e, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]})))
  print("Div => ", (sess.run(f, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]})))


Plus =>  [[6 4 6]
 [2 4 6]]
Minus =>  [[-4  0  0]
 [ 0  0  0]]
Mutiply =>  [[5 4 9]
 [1 4 9]]
Div =>  [[0 1 1]
 [1 1 1]]


In [23]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(2, name="tb_a")
b = tf.constant(3, name="tb_b")
x = tf.add(a, b, name="tb_x")

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs', sess.graph)
  print(sess.run(x))

5


In [24]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.Variable(10, name="x")
y = tf.Variable(20, name="y")
z1 = tf.add(x, y, name="z1")
z2 = tf.multiply(x, y, name="z2")
z3 = tf.multiply(z1, z2, name="z3")

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs', sess.graph)
  print(sess.run(z3))

writer.close()

6000


In [25]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32, shape=[3], name="a")
b = tf.constant([5, 5, 5], tf.float32, name="b")
c = a + b

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs', sess.graph)
  print(sess.run(c, feed_dict={a: [1, 2, 3]}))

writer.close()

[6. 7. 8.]
